spring:
  application:
    name: config-server
  cloud:
    config:
      discovery:
        enabled: true
      label: master
      server:
        git:
          uri: https://gitee.com/zhuzhiou/ebox-config-repo.git
          username: ${git.username}
          password: ${git.password}
    inetutils:
      ignored-interfaces:
        - Microsoft.*
        - Software.*
        - VMware.*
eureka:
  instance:
    prefer-ip-address: true
    lease-expiration-duration-in-seconds: 30
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/
server:
  port: 7001